import { describe, it, expect } from 'vitest';
import { doSearch } from './searchService.js';

describe('searchService (Generated by Jules)', () => {
  it('should return an empty array for any query', () => {
    expect(doSearch('hello')).toEqual([]);
  });
});
