import { describe, it, expect, vi } from 'vitest';
import { searchEndpoint } from './searchController.js';

describe('searchController (Generated by Jules)', () => {
  it('should call res.json with results', () => {
    const req = { query: { q: 'test' } };
    const res = { json: vi.fn() };
    searchEndpoint(req, res);
    expect(res.json).toHaveBeenCalledWith([]);
  });
});
