// Public unsubscribe (token-gated, no API key)
// ─────────────────────────────────────────────────────────────────────────────
// Email recipients click this link from their inbox. Token is HMAC-SHA256
// over (campaign_id|contact_id|email) generated by runner.go buildUnsubURL.
// Validating server-side means we don't need to expose the recipient list
// to attackers — only someone who already received an email can opt out.
//
// Idempotent: re-clicking the same link does nothing (ON CONFLICT DO NOTHING).
// Suppression UNION (commit e000fb9 + caba00a) catches the entry on next
// runner tick.
//
// T3.1 (2026-05-01): extracted verbatim from server.js per ADR-008 / T3.x
// route-mount refactor. Behavior is byte-equivalent to the inline declarations:
//  - same HMAC verify via canonical helper (PR #408 const-time crypto.timingSafeEqual)
//  - same INSERTs into suppression_list + outreach_suppressions
//  - same UPDATE contacts SET status='unsubscribed'
//  - same operator_audit_log row
//  - same 10/min/IP rate-limit semantics (no auth-disabled bypass — recipients
//    of email links are unauthenticated by definition)
// Audit test `tests/audit/gdpr-cascade-shape.test.js` scans both server.js +
// the route module via multi-file lookup (PR #443).
// Contract test `tests/contract/bff-unsubscribe.contract.test.ts` verifies
// the HTTP-level shape end-to-end via `app.listen(0)`.

import { verifyUnsubToken } from '../lib/unsubToken.js'

// S-C1 — resolve the unsubscribe HMAC secret. Returns the secret string,
// or null when BOTH env vars are unset. The handler refuses to verify
// when null instead of falling through to HMAC('') (which would accept
// any forged token). Also asserted at boot in production via server.js
// boot path (importing this same helper).
export function resolveUnsubscribeSecret() {
  const s = process.env.UNSUBSCRIBE_SECRET || process.env.OUTREACH_API_KEY || ''
  return s || null
}

// Module-scoped rate-limit bucket: 10 hits per IP per minute. Was
// previously per-request closure (defeated rate limit since bucket
// reset on every request). Caught by bff-unsubscribe.contract.test.
const _unsubBuckets = new Map()
function _unsubAllow(ip) {
  const now = Date.now()
  const win = 60_000
  const max = 10
  const key = ip || 'unknown'
  const hits = (_unsubBuckets.get(key) || []).filter(t => now - t < win)
  if (hits.length >= max) return false
  hits.push(now)
  _unsubBuckets.set(key, hits)
  return true
}

function unsubPage(message, brandLabel = 'Garaaage') {
  return `<!DOCTYPE html>
<html lang="cs"><head><meta charset="utf-8"><title>Odhlášení — ${brandLabel}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body{font-family:-apple-system,BlinkMacSystemFont,sans-serif;max-width:560px;margin:80px auto;padding:24px;color:#111;line-height:1.5}
h1{font-size:1.4rem;margin:0 0 16px}
p{margin:0 0 12px}
.box{padding:24px;border:1px solid #e5e7eb;border-radius:8px;background:#fafafa}
</style></head>
<body>
<div class="box">
<h1>${brandLabel} — Odhlášení</h1>
<p>${message.replace(/[<>&]/g, c => ({'<':'&lt;','>':'&gt;','&':'&amp;'}[c]))}</p>
<p style="color:#666;font-size:.9rem;margin-top:24px">Pokud jste se odhlásili omylem, kontaktujte nás na uvedeném telefonu nebo emailem.</p>
</div>
</body></html>`
}

/**
 * Mount the public /unsubscribe route on an Express app.
 *
 * @param {import('express').Express} app
 * @param {{
 *   pool: import('pg').Pool,
 *   capture500: (res: import('express').Response, err: unknown, safeError: (e: unknown) => string) => void,
 *   safeError: (e: unknown) => string,
 *   Sentry: { captureException: (e: unknown, ctx?: unknown) => void },
 * }} deps
 */
export function mountUnsubscribeRoutes(app, { pool, capture500, safeError, Sentry }) {
  app.get('/unsubscribe', async (req, res) => {
    const ip = req.ip || req.headers['x-forwarded-for']?.split(',')[0]?.trim() || req.connection?.remoteAddress
    if (!_unsubAllow(ip)) {
      return res.status(429).type('text/plain').send('Příliš mnoho pokusů. Zkuste za chvíli.')
    }

    // Fetch brand_label from operator_settings; fall back to hardcoded value
    let brandLabel = 'Garaaage'
    try {
      const { rows } = await pool.query(
        `SELECT value FROM operator_settings WHERE key='brand_label' LIMIT 1`
      )
      if (rows.length > 0) {
        brandLabel = rows[0].value
      }
    } catch {
      // Silently fall back on DB error
    }

    const c = parseInt(req.query.c, 10)
    const id = parseInt(req.query.id, 10)
    const t = String(req.query.t || '').toLowerCase()

    if (!Number.isFinite(c) || !Number.isFinite(id) || !/^[0-9a-f]{16}$/.test(t)) {
      return res.status(400).type('text/html').send(unsubPage('Odkaz není platný (chybné parametry).', brandLabel))
    }

    // Look up email by contact_id so we can recompute the HMAC.
    let email
    try {
      const { rows } = await pool.query('SELECT email FROM contacts WHERE id=$1', [id])
      if (!rows.length || !rows[0].email) {
        return res.status(404).type('text/html').send(unsubPage('Kontakt nenalezen.', brandLabel))
      }
      email = rows[0].email
    } catch (e) {
      capture500(res, e, safeError); return
    }

    // S-C1 — resolveUnsubscribeSecret() returns null if BOTH env vars are
    // unset. A previous version fell through to HMAC('') and would have
    // accepted any forged token (mass-unsub attack vector). Refuse to
    // verify in that case — return 503 + Sentry alert, no DB writes.
    const secret = resolveUnsubscribeSecret()
    if (!secret) {
      Sentry.captureException(
        new Error('unsubscribe: neither UNSUBSCRIBE_SECRET nor OUTREACH_API_KEY set'),
        { tags: { route: '/unsubscribe', code: 'secret_missing' } },
      )
      return res.status(503).type('text/html').send(unsubPage('Služba dočasně nedostupná. Kontaktujte podporu.', brandLabel))
    }
    // Recompute HMAC via canonical helper (src/lib/unsubToken.js — twin of
    // services/common/token/unsub.go). Constant-time compare via
    // crypto.timingSafeEqual prevents per-byte timing leaks.
    if (!verifyUnsubToken(c, id, email, t, secret)) {
      return res.status(403).type('text/html').send(unsubPage('Odkaz není platný (token).', brandLabel))
    }

    // Idempotent suppression + status update. The suppression_list write is the
    // LOAD-BEARING compliance gate and is NOT best-effort: the Go runner UNIONs
    // suppression_list + outreach_suppressions before every send tick
    // (suppressionFilterSQL in services/campaigns/campaign/runner.go), so once
    // that row exists the recipient is blocked. The later mirror writes ARE
    // best-effort — their failure only delays Go-side sync, it does not
    // un-suppress.
    //
    // MVP-1: belt-and-suspenders. Write to BOTH tables so:
    //  - suppression_list is hit (JS-side reads, /api/suppressions/bulk)
    //  - outreach_suppressions is hit (Go reads in services/contacts/enrichment,
    //    plus migration 005 trigger mirrors to contacts.status — covers the
    //    case where the trigger isn't yet applied to staging/prod).

    // H9 — the load-bearing write MUST succeed before we confirm the opt-out.
    // Previously this INSERT had no `.catch` (unlike the writes below): a throw
    // (e.g. ON CONFLICT with no unique index on suppression_list.email, or any
    // DB error) jumped to the outer catch → Sentry only → then fell through to
    // the UNCONDITIONAL success page, telling the recipient "odhlášení proběhlo
    // úspěšně" while NOTHING was suppressed AND every later write was skipped.
    // On failure we now return 5xx + a retry message instead of a false
    // confirmation, so the recipient is never told they're opted out when they
    // are not.
    try {
      await pool.query(
        `INSERT INTO suppression_list(email, reason, contact_id)
         VALUES(lower(trim($1)), 'link_optout', $2)
         ON CONFLICT(email) DO UPDATE SET reason='link_optout', suppressed_at=now()`,
        [email, id]
      )
    } catch (e) {
      Sentry.captureException(e, { tags: { route: '/unsubscribe', code: 'suppression_write_failed' } })
      return res.status(500).type('text/html').send(
        unsubPage('Odhlášení se teď nepodařilo dokončit. Zkuste to prosím za chvíli znovu, nebo nás kontaktujte na uvedeném telefonu či emailem.', brandLabel)
      )
    }

    // Best-effort mirrors — the load-bearing suppression above already blocks
    // sends via the runner UNION. Each guards its own failure and must NOT
    // block the confirmation page.
    try {
      await pool.query(
        `INSERT INTO outreach_suppressions(email, reason)
         VALUES(lower(trim($1)), 'unsubscribe')
         ON CONFLICT(email) DO NOTHING`,
        [email]
      ).catch(e => {
        // outreach_suppressions table may not exist in dev (Schema B not seeded).
        // Don't surface to Sentry as fatal — the suppression_list write above
        // is the load-bearing one.
        console.warn('[unsubscribe] outreach_suppressions write failed:', e.message)
      })
      await pool.query(`UPDATE contacts SET status='unsubscribed' WHERE id=$1`, [id]).catch(() => {})
      // F2-1: Schema B mirror + thread close. Without these the Go-side
      // contact stays 'active' and outreach_threads keeps producing sends
      // until the next intelligence-loop sync — i.e. the recipient sees
      // the thank-you page but still gets follow-ups for hours/days.
      // Mirrors services/contacts/enrichment/suppress.go SuppressEmail
      // semantics so link-unsub and negative-reply / hard-bounce paths
      // both close threads.
      await pool.query(
        `UPDATE outreach_contacts SET status='suppressed', updated_at=now()
          WHERE email_hash = encode(sha256(lower(trim($1::text))::bytea), 'hex')`,
        [email]
      ).catch(e => {
        console.warn('[unsubscribe] outreach_contacts mirror failed:', e.message)
      })
      await pool.query(
        `UPDATE outreach_threads SET status='closed', updated_at=now()
          WHERE contact_id = (
            SELECT id FROM outreach_contacts
             WHERE email_hash = encode(sha256(lower(trim($1::text))::bytea), 'hex')
          )
            AND status IN ('new','active','paused')`,
        [email]
      ).catch(e => {
        console.warn('[unsubscribe] outreach_threads cascade failed:', e.message)
      })
      // Audit log entry: email redacted from details to minimize PII in audit trail (Art. 5/1/c GDPR)
      await pool.query(
        `INSERT INTO operator_audit_log(action, actor, entity_type, entity_id, details)
         VALUES('unsubscribe_link', 'recipient', 'contact', $1, jsonb_build_object('campaign_id', $2))`,
        [String(id), c]
      ).catch(() => {})
    } catch (e) {
      Sentry.captureException(e, { tags: { route: '/unsubscribe' } })
    }

    res.type('text/html').send(unsubPage('Odhlášení proběhlo úspěšně. Z Vašeho kontaktu nebudou odesílány další zprávy.', brandLabel))
  })
}
