#!/usr/bin/env node
// Generate the daily bot digest as Markdown to stdout.
// Sections: PRs (bot vs user), issues created last 24h, priority distribution,
// top P0 open, blocked-by-bot count.

import { execFileSync } from 'node:child_process';

function gh(args) {
  return execFileSync('gh', args, { encoding: 'utf8' });
}

function jsonGh(args) {
  return JSON.parse(gh(args));
}

const since = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();

// ── Data ─────────────────────────────────────────────────────────
const prs = jsonGh(['pr', 'list', '--state=all', '--limit=200',
  '--json=number,title,author,createdAt,mergedAt,state,labels']);
const issues = jsonGh(['issue', 'list', '--state=all', '--limit=500',
  '--json=number,title,labels,createdAt,closedAt,assignees']);

const prsLast24 = prs.filter((p) => p.createdAt > since);
const botPrs = prsLast24.filter((p) => (p.labels || []).some((l) => l.name === 'automation/bot'));
const userPrs = prsLast24.filter((p) => !(p.labels || []).some((l) => l.name === 'automation/bot'));
const mergedPrs = prsLast24.filter((p) => p.mergedAt && p.mergedAt > since);

const issuesLast24 = issues.filter((i) => i.createdAt > since);
const issuesClosedLast24 = issues.filter((i) => i.closedAt && i.closedAt > since);

const openIssues = issues.filter((i) => !i.closedAt);
const byPriority = { p0: 0, p1: 0, p2: 0, p3: 0, none: 0 };
const bySource = { sentry: 0, 'test-fail': 0, 'health-check': 0, manual: 0, initiative: 0, none: 0 };
const blocked = openIssues.filter((i) => (i.labels || []).some((l) => l.name === 'automation/blocked'));

for (const i of openIssues) {
  const labels = (i.labels || []).map((l) => l.name);
  let p = 'none';
  for (const k of ['p0', 'p1', 'p2', 'p3']) {
    if (labels.includes(`priority/${k}`)) { p = k; break; }
  }
  byPriority[p]++;

  let src = 'none';
  for (const k of ['sentry', 'test-fail', 'health-check', 'manual', 'initiative']) {
    if (labels.includes(`from/${k}`)) { src = k; break; }
  }
  bySource[src]++;
}

const topP0 = openIssues
  .filter((i) => (i.labels || []).some((l) => l.name === 'priority/p0'))
  .sort((a, b) => new Date(a.createdAt) - new Date(b.createdAt))
  .slice(0, 5);

// ── Render ───────────────────────────────────────────────────────
const lines = [];
const date = new Date().toISOString().slice(0, 10);

lines.push(`# Bot Report ${date}`);
lines.push('');
lines.push(`Last 24h activity in **hozan-taher** repo. Auto-generated by \`.github/workflows/daily-digest.yml\`.`);
lines.push('');

lines.push(`## PR activity (24h)`);
lines.push(`- Bot opened: **${botPrs.length}**`);
lines.push(`- User opened: **${userPrs.length}**`);
lines.push(`- Merged: **${mergedPrs.length}**`);
lines.push('');

lines.push(`## Issue activity (24h)`);
lines.push(`- Created: **${issuesLast24.length}**`);
lines.push(`- Closed: **${issuesClosedLast24.length}**`);
lines.push('');

lines.push(`## Open issue distribution`);
lines.push(`### By priority`);
lines.push(`- p0: ${byPriority.p0}`);
lines.push(`- p1: ${byPriority.p1}`);
lines.push(`- p2: ${byPriority.p2}`);
lines.push(`- p3: ${byPriority.p3}`);
lines.push(`- (none): ${byPriority.none}`);
lines.push('');
lines.push(`### By source`);
lines.push(`- sentry: ${bySource.sentry}`);
lines.push(`- test-fail: ${bySource['test-fail']}`);
lines.push(`- health-check: ${bySource['health-check']}`);
lines.push(`- manual: ${bySource.manual}`);
lines.push(`- initiative: ${bySource.initiative}`);
lines.push(`- (none): ${bySource.none}`);
lines.push('');

lines.push(`## Bot status`);
lines.push(`- Open \`automation/blocked\` issues: **${blocked.length}**`);
const open24Bot = prs.filter((p) => p.state === 'OPEN' && (p.labels || []).some((l) => l.name === 'automation/bot'));
lines.push(`- Open \`[bot]\` PRs awaiting review: **${open24Bot.length}**`);
lines.push('');

if (topP0.length > 0) {
  lines.push(`## Top P0 open`);
  for (const i of topP0) {
    lines.push(`- #${i.number} ${i.title}`);
  }
  lines.push('');
}

lines.push(`---`);
lines.push(`Run details: ${process.env.GITHUB_SERVER_URL || 'https://github.com'}/${process.env.GITHUB_REPOSITORY || ''}/actions/runs/${process.env.GITHUB_RUN_ID || ''}`);

console.log(lines.join('\n'));
