#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════
# ML1.4 — DKIM key generation for Mail Lab providers.
# ════════════════════════════════════════════════════════════════════════
#
# Generates 2048-bit RSA DKIM keys per provider domain. Outputs:
#   infra/mail-lab/dkim/<domain>/mail.private     (PEM, mode 0600)
#   infra/mail-lab/dkim/<domain>/mail.txt         (DNS TXT record)
#   infra/mail-lab/postfix/opendkim/keytable      (OpenDKIM KeyTable, rebuilt)
#   infra/mail-lab/postfix/opendkim/signingtable  (OpenDKIM SigningTable, rebuilt)
#
# Side effect: patches infra/mail-lab/dns/unbound.conf in-place, replacing
# the PLACEHOLDER (or previous key) for each domain with the real public key.
#
# Idempotent: re-run skips key generation when mail.private + mail.txt both
# exist and the private key passes `openssl rsa -check`. Keys are still used
# to rebuild keytable/signingtable and patch unbound.conf.
#
# Mail Lab is sealed (no egress); these keys are intentionally committed
# to the repo. NEVER reuse for production. See infra/mail-lab/README.md.
#
# Usage:
#   bash scripts/mail-lab/init-dkim.sh seznam.lab
#   bash scripts/mail-lab/init-dkim.sh seznam.lab gmail.lab outlook.lab
#
# Exit codes:
#   0  success (or already present)
#   1  generation or validation error
#   2  argument error

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DKIM_DIR="${ROOT}/infra/mail-lab/dkim"
UNBOUND_CONF="${ROOT}/infra/mail-lab/dns/unbound.conf"
OPENDKIM_DIR="${ROOT}/infra/mail-lab/postfix/opendkim"
SELECTOR="mail"
KEY_BITS=2048

if [[ $# -eq 0 ]]; then
  echo "usage: $0 <domain> [<domain>...]" >&2
  exit 2
fi

# Need openssl on PATH.
if ! command -v openssl >/dev/null 2>&1; then
  echo "ERROR: openssl not on PATH" >&2
  exit 1
fi

mkdir -p "${OPENDKIM_DIR}"

# ── generate (or validate) one key pair ─────────────────────────────────────
gen_key() {
  local domain="$1"
  local target="${DKIM_DIR}/${domain}"
  local priv="${target}/${SELECTOR}.private"
  local txt="${target}/${SELECTOR}.txt"

  if [[ -f "${priv}" ]] && [[ -f "${txt}" ]]; then
    if openssl rsa -check -in "${priv}" -noout 2>/dev/null; then
      echo "── ${domain}: existing valid key — skipping generation"
      # Always enforce correct permissions even if key was committed without them.
      chmod 0600 "${priv}"
    else
      echo "── ${domain}: existing key invalid — regenerating"
      rm -f "${priv}" "${txt}"
    fi
  fi

  if [[ ! -f "${priv}" ]]; then
    mkdir -p "${target}"
    echo "── ${domain}: generating ${KEY_BITS}-bit RSA..."

    openssl genrsa -out "${priv}" "${KEY_BITS}" 2>/dev/null
    chmod 0600 "${priv}"

    local pubkey
    pubkey=$(openssl rsa -in "${priv}" -pubout -outform DER 2>/dev/null | base64 | tr -d '\n')
    local payload="v=DKIM1; k=rsa; p=${pubkey}"

    {
      echo "; DKIM key for ${SELECTOR}._domainkey.${domain}"
      echo "; Generated by scripts/mail-lab/init-dkim.sh — test-only key, NOT for prod."
      printf '%s._domainkey.%s.  IN  TXT  ( \n' "${SELECTOR}" "${domain}"
      # Split into 200-char chunks for BIND/RFC5321 compliance.
      local chunk_size=200
      local i=0
      while [[ ${i} -lt ${#payload} ]]; do
        local chunk="${payload:${i}:${chunk_size}}"
        echo "    \"${chunk}\""
        i=$((i + chunk_size))
      done
      echo ") ; ${KEY_BITS}-bit"
      echo
      echo "; Single-line form (for unbound local-data):"
      echo "; local-data: \"${SELECTOR}._domainkey.${domain}. IN TXT \\\"${payload}\\\"\""
    } > "${txt}"

    echo "── ${domain}: wrote ${priv} (mode 0600) + ${txt}"
  fi
}

# ── patch unbound.conf DKIM TXT for one domain ──────────────────────────────
patch_unbound() {
  local domain="$1"
  local priv="${DKIM_DIR}/${domain}/${SELECTOR}.private"

  [[ -f "${UNBOUND_CONF}" ]] || { echo "── WARNING: ${UNBOUND_CONF} not found — skip DNS patch"; return 0; }

  local pubkey
  pubkey=$(openssl rsa -in "${priv}" -pubout -outform DER 2>/dev/null | base64 | tr -d '\n')
  # The unbound local-data line — inner double-quotes escaped with backslash.
  # We build this as a literal string and use printf to write it, avoiding
  # shell variable substitution eating the backslashes.
  local new_line
  printf -v new_line '  local-data: "%s._domainkey.%s. IN TXT \\"v=DKIM1; k=rsa; p=%s\\""' \
    "${SELECTOR}" "${domain}" "${pubkey}"

  local needle="${SELECTOR}._domainkey.${domain}"

  if grep -qF "${needle}" "${UNBOUND_CONF}"; then
    local tmp
    tmp="$(mktemp)"
    # Replace the whole line containing the needle (awk is portable).
    # We write the replacement line to a temp file then read it in awk to
    # avoid escaping hell when passing complex strings via -v.
    local repl_file
    repl_file="$(mktemp)"
    printf '%s\n' "${new_line}" > "${repl_file}"
    awk -v needle="${needle}" -v replfile="${repl_file}" '
      index($0, needle) > 0 {
        while ((getline line < replfile) > 0) print line
        close(replfile)
        next
      }
      { print }
    ' "${UNBOUND_CONF}" > "${tmp}"
    mv "${tmp}" "${UNBOUND_CONF}"
    rm -f "${repl_file}"
    echo "── ${domain}: unbound.conf DKIM TXT updated"
  else
    printf '%s\n' "${new_line}" >> "${UNBOUND_CONF}"
    echo "── ${domain}: unbound.conf DKIM TXT appended"
  fi
}

# ── rebuild OpenDKIM keytable + signingtable ─────────────────────────────────
rebuild_opendkim_tables() {
  local keytable="${OPENDKIM_DIR}/keytable"
  local signingtable="${OPENDKIM_DIR}/signingtable"

  : > "${keytable}"
  : > "${signingtable}"

  for d_path in "${DKIM_DIR}"/*/; do
    local d
    d="$(basename "${d_path}")"
    local priv="${d_path}${SELECTOR}.private"

    [[ -f "${priv}" ]] || continue
    openssl rsa -check -in "${priv}" -noout 2>/dev/null || continue

    # docker-mailserver mounts keys at this path inside the container.
    local container_key="/tmp/docker-mailserver/opendkim/keys/${d}/${SELECTOR}.private"

    # KeyTable: <selector>._domainkey.<domain>  <domain>:<selector>:<key_path>
    printf '%s._domainkey.%s\t%s:%s:%s\n' \
      "${SELECTOR}" "${d}" "${d}" "${SELECTOR}" "${container_key}" >> "${keytable}"

    # SigningTable: *@<domain>  <selector>._domainkey.<domain>
    printf '*@%s\t%s._domainkey.%s\n' \
      "${d}" "${SELECTOR}" "${d}" >> "${signingtable}"
  done

  echo "── keytable rebuilt → ${keytable}"
  echo "── signingtable rebuilt → ${signingtable}"
}

# ── Main ────────────────────────────────────────────────────────────────────
for domain in "$@"; do
  gen_key "${domain}"
  patch_unbound "${domain}"
done

rebuild_opendkim_tables

echo "── Done. ${#@} domain(s) processed."
