#!/usr/bin/env bash
# scripts/mail-lab/replay-campaign.sh — time-accelerated reply replay (OP2.2).
#
# Reads an arrival-curve.json (from arrival-curve.mjs) and pushes each
# scheduled fixture into the operator's lab inbox, sleeping the curve's
# delay between each. Supports --accel for compressing real time:
#
#   --accel 1     → real-time (24h scenario plays out over 24h)
#   --accel 60    → 24h scenario in 24min
#   --accel 1440  → 24h scenario in 1min
#   --accel 86400 → 24h scenario in 1s (test mode)
#
# Usage:
#   bash scripts/mail-lab/replay-campaign.sh <curve.json> <mailbox> [--password X] [--accel N] [--dry-run]
#
# Defaults:
#   accel = 1 (real-time)
#   no password (must supply via env or flag)
#
# Exit codes:
#   0 success
#   1 curve file unreadable
#   2 missing required arg
#   3 IMAP append failure (propagated from seed-replies.mjs)

set -euo pipefail

CURVE=""
MAILBOX=""
PASSWORD="${LAB_OPERATOR_PASSWORD:-}"
ACCEL=1
DRY_RUN=0

usage() {
  cat <<EOF
Usage: $0 <curve.json> <mailbox> [--password X] [--accel N] [--dry-run]

Replays a curve generated by arrival-curve.mjs into a Mail Lab inbox,
honoring the time-acceleration factor.

Args:
  <curve.json>        path to JSON array from arrival-curve.mjs
  <mailbox>           target IMAP user (e.g. op@gmail.lab)
  --password X        IMAP password (env: LAB_OPERATOR_PASSWORD)
  --accel N           time compression factor (default: 1 = real-time)
  --dry-run           print what would happen, don't deliver
  -h, --help          this message
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) usage; exit 0 ;;
    --password) PASSWORD="$2"; shift 2 ;;
    --accel) ACCEL="$2"; shift 2 ;;
    --dry-run) DRY_RUN=1; shift ;;
    --) shift; break ;;
    -*) echo "unknown flag: $1" >&2; exit 2 ;;
    *)
      if [[ -z "$CURVE" ]]; then CURVE="$1"
      elif [[ -z "$MAILBOX" ]]; then MAILBOX="$1"
      else echo "unexpected positional: $1" >&2; exit 2
      fi
      shift
      ;;
  esac
done

if [[ -z "$CURVE" || -z "$MAILBOX" ]]; then
  usage; exit 2
fi
if [[ ! -f "$CURVE" ]]; then
  echo "curve file not found: $CURVE" >&2
  exit 1
fi
if (( DRY_RUN == 0 )) && [[ -z "$PASSWORD" ]]; then
  echo "--password (or LAB_OPERATOR_PASSWORD env) required for non-dry-run" >&2
  exit 2
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# Validate inputs to prevent shell injection (#268 self-review CRITICAL).
# Mailbox must be a normal email address; reject anything that could be
# expanded by sub-shell or break argv parsing of nested commands.
if [[ ! "$MAILBOX" =~ ^[a-zA-Z0-9._@+-]+$ ]]; then
  echo "[replay] ERROR: mailbox contains illegal characters: $MAILBOX" >&2
  exit 2
fi
# Resolve curve path through realpath to canonicalize and reject any path
# with shell metachars; pass via env var to nested node invocation
# instead of string interpolation.
if ! CURVE_REAL="$(cd "$(dirname "$CURVE")" && pwd)/$(basename "$CURVE")"; then
  echo "[replay] ERROR: cannot resolve curve path: $CURVE" >&2
  exit 1
fi

echo "[replay] curve=$CURVE_REAL mailbox=$MAILBOX accel=${ACCEL}x dry-run=$DRY_RUN"

# Read curve via Node — pass path through env var (no shell interpolation
# into the source code) and use process.env.CURVE, not '$CURVE'.
ENTRIES=$(CURVE_PATH="$CURVE_REAL" node -e '
  const fs = require("fs")
  const curve = JSON.parse(fs.readFileSync(process.env.CURVE_PATH, "utf8"))
  if (!Array.isArray(curve)) { console.error("curve not an array"); process.exit(1) }
  for (const e of curve) {
    process.stdout.write(`${e.delay_ms}\t${e.fixture_category}\t${e.index}\n`)
  }
')

PREV_DELAY=0
COUNT=0
while IFS=$'\t' read -r DELAY_MS CATEGORY INDEX; do
  [[ -z "$DELAY_MS" ]] && continue
  GAP_MS=$(( DELAY_MS - PREV_DELAY ))
  PREV_DELAY=$DELAY_MS
  # Sleep gap_ms / accel — use node setTimeout instead of bash `sleep`
  # because POSIX sleep doesn't accept fractional seconds (#268 self-review HIGH).
  # macOS BSD + GNU coreutils accept fractional, but NetBSD/Solaris/busybox
  # truncate or error. Node is portable.
  SLEEP_MS=$(awk -v g="$GAP_MS" -v a="$ACCEL" 'BEGIN { printf "%d\n", g / a }')
  if (( DRY_RUN )); then
    echo "[replay] DRY: sleep ${SLEEP_MS}ms → inject ${CATEGORY}/${INDEX}"
  else
    SLEEP_MS_VAL="$SLEEP_MS" node -e 'setTimeout(() => {}, parseInt(process.env.SLEEP_MS_VAL, 10))'
    node "$REPO_ROOT/scripts/operator-practice/seed-replies.mjs" \
      --mailbox "$MAILBOX" \
      --password "$PASSWORD" \
      --count 1 \
      --category "$CATEGORY" \
      --source placeholder \
      --host "${LAB_IMAP_HOST:-localhost}" \
      --port "${LAB_IMAP_PORT:-25993}" \
      || { echo "[replay] inject failed at index ${INDEX}" >&2; exit 3; }
    echo "[replay] +${SLEEP_S}s : ${CATEGORY}/${INDEX} appended"
  fi
  COUNT=$(( COUNT + 1 ))
done <<< "$ENTRIES"

echo "[replay] done — ${COUNT} reply(ies) processed"
