// @linkage-allowed: discipline ratchet — scans files dynamically (not via static imports)
// Lighthouse budgets — per-route Core Web Vitals from reports/lighthouse/summary.json.
// Generated by: pnpm preview & LH_BASE=http://localhost:4173 node scripts/lighthouse.mjs
// CI runs both before vitest. Adjust budgets only on documented perf wins.

import { describe, it, expect } from 'vitest'
import { readFileSync, existsSync } from 'node:fs'

const PATH = 'reports/lighthouse/summary.json'

// Budgets are CURRENT-NUMBER + headroom, NOT goals. Improving perf?
// Tighten budget after the win. Goal is to catch regressions, not document
// the dream state. Real perf debt tracked in reports/lighthouse/BASELINE.md.
const BUDGET = {
  perf:    60,        // current min 67; budget 60 catches a ~10% regression
  lcp:     8_000,     // current max ~6s; live API + chart render
  cls:     0.15,      // current max 0.12 on /mailboxes (live counters reflow) — fix planned
  tbt:     800,       // current max ~500
  fcp:     4_500,     // current max ~4s
}

// describe.skipIf still evaluates the callback at collection time to register
// test names, so the body must not throw when PATH is missing. Load lazily.
describe.skipIf(!existsSync(PATH))('Lighthouse perf budgets', () => {
  const sum = existsSync(PATH) ? JSON.parse(readFileSync(PATH, 'utf8')) : { routes: [] }
  for (const r of sum.routes) {
    describe(`route ${r.path}`, () => {
      it(`perf ≥ ${BUDGET.perf} (got ${r.perf})`, () => {
        expect(r.perf, `${r.path} perf=${r.perf} below budget`).toBeGreaterThanOrEqual(BUDGET.perf)
      })
      it(`LCP ≤ ${BUDGET.lcp}ms (got ${Math.round(r.lcp)})`, () => {
        expect(r.lcp, `${r.path} LCP=${r.lcp}ms`).toBeLessThanOrEqual(BUDGET.lcp)
      })
      it(`CLS ≤ ${BUDGET.cls} (got ${r.cls.toFixed(3)})`, () => {
        expect(r.cls).toBeLessThanOrEqual(BUDGET.cls)
      })
      it(`TBT ≤ ${BUDGET.tbt}ms (got ${Math.round(r.tbt)})`, () => {
        expect(r.tbt).toBeLessThanOrEqual(BUDGET.tbt)
      })
      it(`FCP ≤ ${BUDGET.fcp}ms (got ${Math.round(r.fcp)})`, () => {
        expect(r.fcp).toBeLessThanOrEqual(BUDGET.fcp)
      })
    })
  }
})
