#!/bin/zsh

set -euo pipefail

TARGET_FILE="${1:-.env.fastmail.local}"
INPUT_ALIAS_DOMAIN="${2:-${ALIAS_DOMAIN:-}}"
INPUT_FASTMAIL_GATEWAY_ADDRESS="${3:-${FASTMAIL_GATEWAY_ADDRESS:-}}"
INPUT_RECIPIENT_MAILBOX_ADDRESS="${4:-${RECIPIENT_MAILBOX_ADDRESS:-}}"
INPUT_SMTP_PASSWORD="${5:-${SMTP_PASSWORD:-}}"

if [[ "$TARGET_FILE" == "--help" || "$TARGET_FILE" == "-h" ]]; then
  cat <<'EOF'
Usage:
  ./scripts/prepare-fastmail-env.sh [target_file] [alias_domain] [gateway_email] [recipient_email] [smtp_app_password]

Inputs can be provided either:
  - interactively (prompted), or
  - via positional arguments, or
  - via env vars: ALIAS_DOMAIN, FASTMAIL_GATEWAY_ADDRESS, RECIPIENT_MAILBOX_ADDRESS, SMTP_PASSWORD

If ALIAS_DOMAIN is omitted, it is derived from FASTMAIL_GATEWAY_ADDRESS (domain part after "@").
EOF
  exit 0
fi

prompt_value() {
  local var_name="$1"
  local prompt_text="$2"
  local secret="${3:-false}"
  local current_value="${4:-}"
  local value=""

  if [[ -n "${current_value// }" ]]; then
    printf '%s' "$current_value"
    return
  fi

  if [[ ! -t 0 ]]; then
    echo "FAIL: missing required value for $var_name in non-interactive mode"
    echo "TIP: pass args or export env vars. Try: ./scripts/prepare-fastmail-env.sh --help"
    exit 1
  fi

  if [[ "$secret" == "true" ]]; then
    read -r -s "?$prompt_text: " value
    echo
  else
    read -r "?$prompt_text: " value
  fi

  if [[ -z "${value// }" ]]; then
    echo "FAIL: $var_name must not be empty"
    exit 1
  fi

  printf '%s' "$value"
}

FASTMAIL_GATEWAY_ADDRESS="$(prompt_value "FASTMAIL_GATEWAY_ADDRESS" "FASTMAIL_GATEWAY_ADDRESS" "false" "$INPUT_FASTMAIL_GATEWAY_ADDRESS")"
RECIPIENT_MAILBOX_ADDRESS="$(prompt_value "RECIPIENT_MAILBOX_ADDRESS" "RECIPIENT_MAILBOX_ADDRESS" "false" "$INPUT_RECIPIENT_MAILBOX_ADDRESS")"
SMTP_PASSWORD="$(prompt_value "SMTP_PASSWORD" "SMTP_PASSWORD (Fastmail app password)" "true" "$INPUT_SMTP_PASSWORD")"

ALIAS_DOMAIN="$INPUT_ALIAS_DOMAIN"
if [[ -z "${ALIAS_DOMAIN// }" ]]; then
  ALIAS_DOMAIN="${FASTMAIL_GATEWAY_ADDRESS##*@}"
fi
[[ -n "${ALIAS_DOMAIN// }" ]] || {
  echo "FAIL: ALIAS_DOMAIN must not be empty"
  exit 1
}

cat > "$TARGET_FILE" <<EOF
# Generated by scripts/prepare-fastmail-env.sh
# Safe to edit locally. Do not commit this file.

LISTEN_ADDR=:8080
ALIAS_DOMAIN=$ALIAS_DOMAIN
DATA_DIR=./data
DATA_ENCRYPTION_KEY_B64=L3r/Mn1I5wW5sfZBlJ0zzGU5yM1bl2HHQo1R1lIRu+k=

DELIVERY_MODE=smtp

SMTP_HOST=smtp.fastmail.com
SMTP_PORT=587
SMTP_USERNAME=$FASTMAIL_GATEWAY_ADDRESS
SMTP_PASSWORD=$SMTP_PASSWORD
SMTP_HELLO_DOMAIN=$ALIAS_DOMAIN
SMTP_REQUIRE_STARTTLS=true
SMTP_CONNECT_TIMEOUT_SECONDS=10

IMAP_HOST=imap.fastmail.com
IMAP_PORT=993
IMAP_USERNAME=$FASTMAIL_GATEWAY_ADDRESS
IMAP_PASSWORD=$SMTP_PASSWORD
IMAP_TIMEOUT_SECONDS=10

MAX_RECIPIENTS=10
MAX_MESSAGE_BYTES=131072

DEV_API_TOKEN=dev-token
INTAKE_API_TOKEN=
DEV_USER_ID=user-dev
DEV_TENANT_ID=tenant-dev
DEV_USER_EMAIL=$FASTMAIL_GATEWAY_ADDRESS

FASTMAIL_GATEWAY_ADDRESS=$FASTMAIL_GATEWAY_ADDRESS
RECIPIENT_MAILBOX_ADDRESS=$RECIPIENT_MAILBOX_ADDRESS
INBOUND_TEST_MAILBOX_ADDRESS=$FASTMAIL_GATEWAY_ADDRESS
EOF

echo "Wrote $TARGET_FILE"
echo "Next:"
echo "./scripts/check-fastmail-env.sh $TARGET_FILE"
