import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';
import { globSync } from 'glob';

console.log('🤖 ZAHÁJENÍ POC: JULES (Asynchronní Noční TDD Agent) 🤖\n');

console.log('1. [03:00 AM] Jules se probouzí a scanuje topologii...');
const manifests = globSync('spine/**/vektor.json');
let targetNode = '';
let targetDir = '';
let targetManifestData: any = null;

for (const m of manifests) {
  const data = JSON.parse(fs.readFileSync(m, 'utf8'));
  if (data.state === 'pending' && !targetNode) {
    targetNode = data.id;
    targetDir = path.dirname(m);
    targetManifestData = data;
    break;
  }
}

if (!targetNode) {
  console.log('Nenalezen žádný pending uzel. Končím.');
  process.exit(0);
}

console.log(`2. Nalezen čekající (pending) uzel: '${targetNode}' v ose '${targetManifestData.story_axis}'.`);
console.log(`3. Jules autonomně generuje byznysovou logiku a E2E testy (Test-Driven Development)...`);

// Generování logiky
const logicCode = `// AUTO-GENERATED BY JULES
export function init${targetNode.replace(/-/g, '')}() {
  return { status: 'online', node: '${targetNode}' };
}
`;
fs.writeFileSync(path.join(targetDir, 'logic.ts'), logicCode, 'utf8');

// Generování testu
const testCode = `// AUTO-GENERATED BY JULES
import { describe, it, expect } from 'vitest';
import { init${targetNode.replace(/-/g, '')} } from './logic';

describe('${targetNode} node', () => {
  it('should be initialized correctly by Jules', () => {
    const instance = init${targetNode.replace(/-/g, '')}();
    expect(instance.status).toBe('online');
    expect(instance.node).toBe('${targetNode}');
  });
});
`;
fs.writeFileSync(path.join(targetDir, 'logic.test.ts'), testCode, 'utf8');

console.log(`4. Jules aktualizuje vektor.json (mapování a aktivace)...`);
if (!targetManifestData.facets) targetManifestData.facets = {};
if (!targetManifestData.facets.logic) targetManifestData.facets.logic = [];
if (!targetManifestData.facets.tests) targetManifestData.facets.tests = [];

targetManifestData.facets.logic.push('./logic.ts');
targetManifestData.facets.tests.push('./logic.test.ts');
targetManifestData.state = 'active';

fs.writeFileSync(path.join(targetDir, 'vektor.json'), JSON.stringify(targetManifestData, null, 2), 'utf8');

console.log(`5. [03:01 AM] Jules spouští ověřovací proces (Audit & Vitest)...`);
try {
  const auditOut = execSync('npm run ag:audit', { encoding: 'utf8' });
  console.log('✅ Architektura je po zásahu AI stále čistá!');
  
  const testOut = execSync('npm run test', { encoding: 'utf8' });
  console.log(`✅ Testy pro uzel '${targetNode}' prošly úspěšně!`);
  
  console.log('\n🎉 POC JULES DOKONČEN: Repozitář se sám vyvíjí, generuje testy a zprovozňuje pending featury bez zásahu lidské ruky.');
} catch (e: any) {
  console.log('❌ Něco selhalo při ověřování:');
  console.log(e.stdout);
}
