import * as fs from 'fs';
import * as path from 'path';
import { glob } from 'glob';

export class DocGenerator {
  private rootDir: string;

  constructor(rootDir: string) {
    this.rootDir = rootDir;
  }

  async generate(): Promise<void> {
    const jsonFiles = await glob('spine/**/vektor.json', { cwd: this.rootDir });
    
    let output = '# 🤖 Autogenerated Vector-Tree Documentation\n\n';
    output += 'Tento dokument je plně generován automaticky na základě fyzických uzlů a jejich sémantických manifestů (`vektor.json`).\n\n';
    
    // Seskupit uzly podle osy (story axis)
    const axes: Record<string, any[]> = {};
    
    for (const file of jsonFiles) {
      const fullPath = path.join(this.rootDir, file);
      try {
        const manifest = JSON.parse(fs.readFileSync(fullPath, 'utf8'));
        const axis = manifest.story_axis || 'unknown';
        if (!axes[axis]) axes[axis] = [];
        axes[axis].push(manifest);
      } catch (e) {
        console.warn(`Could not parse ${file}`);
      }
    }

    for (const [axis, nodes] of Object.entries(axes)) {
      output += `## 🪐 Osa: ${axis.toUpperCase()}\n\n`;
      for (const node of nodes) {
        output += `### Uzel: \`${node.id}\`\n`;
        output += `- **Stav:** ${node.state}\n`;
        
        if (node.legacy_metadata) {
          const m = node.legacy_metadata;
          if (m.identita) output += `- **Identita:** ${m.identita}\n`;
          if (m.promise) output += `- **Slib (Promise):** ${m.promise}\n`;
          if (m.loreLine) output += `- **Lore:** ${m.loreLine}\n`;
        }
        
        if (node.facets) {
          output += `- **Fyzické soubory:**\n`;
          for (const [key, files] of Object.entries(node.facets)) {
             output += `  - *${key}*: ${(files as string[]).join(', ')}\n`;
          }
        }
        output += '\n';
      }
    }
    
    fs.writeFileSync(path.join(this.rootDir, 'docs', 'reference', 'autodocs.md'), output, 'utf8');
    console.log('SUCCESS: Auto-documentation generated at docs/reference/autodocs.md');
}
